version: 1.20.1.{build}
branches:
  only:
  - default
clone_folder: c:\projects\Npackd
environment:
  version: 1.20.1
  matrix:
  - bits: 32
  - bits: 64
install:
- AppVeyorInstall.bat %bits%
build_script:
- AppVeyorBuild.bat %bits%
test_script:
- AppVeyorTest.bat %bits%