version: 1.20.1.{build}
branches:
  only:
  - default
clone_folder: c:\projects\Npackd
environment:
  matrix:
  - p: npackd-dev-i686-w64
    bits: 32
    mingw: C:\Program Files (x86)\MinGW-w64_i686_SJLJ_POSIX_threads
  - p: npackd-dev-x86_64-w64
    bits: 64
    mingw: C:\Program Files (x86)\MinGW-w64_x86_64_SEH_POSIX_threads
install:
- msiexec.exe /qn /i http://bit.ly/npackdcl-1_19_13
- SET NPACKD_CL=C:\Program Files (x86)\NpackdCL
- '"%npackd_cl%\ncl" add-repo --url=https://npackd.appspot.com/rep/recent-xml'
- '"%npackd_cl%\ncl" add-repo --url=https://npackd.appspot.com/rep/xml?tag=libs'
- '"%npackd_cl%\ncl" detect'
- '"%npackd_cl%\ncl" set-install-dir -f "C:\Program Files (x86)"'
- '"%npackd_cl%\ncl" add -p %p% -v 1.20.1'
build_script:
- cd wpmcpp && "%mingw%\bin\mingw32-make.exe" zip msi PROFILE=release%bits%
artifacts:
- path: wpmcpp\build\$(bits)\release\Npackd$(bits)-1.20.1.msi
- path: wpmcpp\build\$(bits)\release\Npackd$(bits)-1.20.1.zip
- path: wpmcpp\build\$(bits)\release\Npackd$(bits)-1.20.1.map